# Copyright (c) 2026, ahmedamin and contributors
# For license information, please see license.txt

"""Shared factories and helpers for the custom_webshop test suite.

Mirrors the module-level `make_*` convention used by
contact_enhancements/tests, so a Customer built here satisfies the same
mandatory-field rules that app enforces site-wide.
"""

import contextlib
import random

import frappe

from custom_webshop.signup import settings as signup_settings


def unique_email(prefix="wstest"):
	"""Return an email address guaranteed not to collide with existing data."""
	return f"{prefix}-{frappe.generate_hash(length=10)}@example.com"


def unique_name(prefix="Testuser"):
	"""Return a three-part name that passes both the part-count rule and
	contact_enhancements' Arabic rules (Latin letters only, no digits)."""
	suffix = frappe.generate_hash(length=6)
	# generate_hash can contain digits, which rule 4 rejects; map to letters.
	letters = "".join(chr(ord("a") + int(c, 16) % 26) for c in suffix)
	return f"{prefix} Middle {letters.capitalize()}"


# Walked from a random starting point rather than from zero. The counter
# alone is collision-free *within* a run, but it hands out the same
# numbers on every run - and the flows that complete a signup commit, so
# the accounts they create outlive the transaction. The second run then
# collided with the first on `Webshop Account Identity.phone_e164` and
# `User.mobile_no`, both uniquely indexed, and failed for reasons that
# had nothing to do with the code under test.
_PHONE_BASE = random.randrange(10_000_000, 90_000_000)
_PHONE_COUNTER = {"value": 0}


def unique_phone():
	"""Return a distinct, valid Egyptian mobile number for each call.

	Egyptian mobiles are 010/011/012/015 plus exactly 8 digits, so the
	space walked here is 010 + 8 digits, which keeps every number valid,
	unique within a run, and near-certainly unused by any earlier one.
	"""
	_PHONE_COUNTER["value"] += 1
	return "010{:08d}".format((_PHONE_BASE + _PHONE_COUNTER["value"]) % 100_000_000)


def make_contact(first_name=None, email=None, phone=None, customer=None, **kwargs):
	"""Insert a Contact, optionally linked to a Customer.

	Args:
		first_name: Contact first name; a valid generated name by default.
		email: primary email to append, if any.
		phone: primary mobile to append, if any.
		customer: Customer name to Dynamic-Link to, if any.
		**kwargs: extra fields set on the document.

	Returns:
		The inserted Contact document.
	"""
	contact = frappe.new_doc("Contact")
	contact.first_name = first_name or unique_name("Contact")
	if email:
		contact.append("email_ids", {"email_id": email, "is_primary": 1})
	if phone:
		contact.append("phone_nos", {"phone": phone, "is_primary_mobile_no": 1})
	if customer:
		contact.append("links", {"link_doctype": "Customer", "link_name": customer})
	contact.update(kwargs)
	contact.flags.ignore_permissions = True
	contact.insert()
	return contact


def make_customer(customer_name=None, contact=None, **kwargs):
	"""Insert a Customer that satisfies contact_enhancements' mandatory fields.

	`customer_primary_address` is left unset - as it is for every Customer
	the signup flow creates - so `ignore_mandatory` is required, exactly
	the way contact_enhancements' own test helpers handle it.

	Args:
		customer_name: the Customer's name; generated by default.
		contact: a Contact name to use as primary contact.
		**kwargs: extra fields set on the document.

	Returns:
		The inserted Customer document.
	"""
	customer = frappe.new_doc("Customer")
	customer.update(
		{
			"customer_name": customer_name or unique_name("Customer"),
			"customer_type": "Individual",
			"customer_group": signup_settings.get_customer_group(),
			"territory": signup_settings.get_territory(),
			"customer_primary_contact": contact,
			**kwargs,
		}
	)
	customer.flags.ignore_mandatory = True
	customer.flags.ignore_permissions = True
	customer.insert()
	return customer


def make_customer_with_contact(customer_name=None, phone=None, email=None, contact_name=None):
	"""Insert a linked Contact + Customer pair, the shape signup produces.

	Args:
		customer_name: the Customer's name; generated by default.
		phone: primary mobile for the Contact.
		email: primary email for the Contact.
		contact_name: the Contact's first name; defaults to customer_name.

	Returns:
		A (customer, contact) tuple of inserted documents.
	"""
	customer_name = customer_name or unique_name("Customer")
	contact = make_contact(first_name=contact_name or customer_name, email=email, phone=phone)
	customer = make_customer(customer_name=customer_name, contact=contact.name)
	contact.reload()
	contact.append("links", {"link_doctype": "Customer", "link_name": customer.name})
	contact.flags.ignore_permissions = True
	contact.save()
	return customer, contact


def make_customer_sharing_a_phone(phone, customer_name=None):
	"""A second Customer reachable by a number another Contact already holds.

	Two Contacts cannot both carry one mobile - contact_enhancements
	enforces that with a unique index - so the obvious fixture for "two
	customers, one phone" is no longer insertable. That shape still exists
	in this database, though: `Customer.mobile_no` is normally a read-only
	`fetch_from` mirror of the primary Contact, and rows written straight
	to the column with `db_set` bypass it. `matching.find_customers_by_phone`
	searches that column for exactly this reason, so a Customer built this
	way is found by the same query and produces the same ambiguity - which
	is what the tests using it are about.

	Written with `db.set_value` rather than on the document because the
	field is read-only; a normal save would discard it.

	Args:
		phone: the number, in any written form.
		customer_name: the Customer's name; generated by default.

	Returns:
		The inserted Customer document, reloaded.
	"""
	contact = make_contact(first_name=customer_name or unique_name("Sharer"), phone=unique_phone())
	customer = make_customer(customer_name=customer_name, contact=contact.name)
	contact.reload()
	contact.append("links", {"link_doctype": "Customer", "link_name": customer.name})
	contact.flags.ignore_permissions = True
	contact.save()

	frappe.db.set_value("Customer", customer.name, "mobile_no", phone, update_modified=False)
	customer.reload()
	return customer


def answer_name_card(client, envelope, use_submitted=False):
	"""Answer the "which name?" card, when one was offered.

	Saying yes to a record and saying yes to its spelling are separate
	answers, so `decide` returns a second card whenever the two names
	differ. Tests that only care about the outcome pass through it with
	"keep what the record says", which is the no-op choice.

	Args:
		client: the SignupClient.
		envelope: whatever `decide` returned.
		use_submitted: True to put the typed name on the account.

	Returns:
		The envelope after answering, or the one passed in when no card
		was offered.
	"""
	from custom_webshop.api import signup as signup_api

	if not (envelope.get("data") or {}).get("name_choice"):
		return envelope

	return client.call(signup_api.choose_name, use_submitted=use_submitted)


@contextlib.contextmanager
def capture_otps():
	"""Intercept passcode delivery and record the codes.

	The codes are never returned by any endpoint and never stored in
	plaintext, which is the point - so a test that needs to submit one has
	to stand where the sender stands. Patching the two senders is also a
	faithful stand-in for delivery: everything up to and including
	`otp.issue` runs for real.

	Yields:
		A dict mapping "email"/"phone" to the most recent code sent.
	"""
	from unittest.mock import patch

	codes = {}

	def fake_email(doc, code):
		codes["email"] = code

	def fake_phone(doc, code):
		codes["phone"] = code

	with (
		patch("custom_webshop.api.signup.notifications.send_email_otp", side_effect=fake_email),
		patch("custom_webshop.api.signup.notifications.send_phone_otp", side_effect=fake_phone),
	):
		yield codes


class SignupClient:
	"""Drives the signup API the way one browser would.

	Exists because the flow binds a signup to the browser holding its
	httpOnly cookie, and there is no request object in a test. Each client
	remembers the binding secret its own `start` was issued and restores
	it before every later call, so two clients in one test are genuinely
	two different browsers - which is what the isolation and race tests
	need.
	"""

	def __init__(self):
		self.signup_id = None
		self.secret = None
		self.codes = {}

	def _restore_binding(self):
		frappe.local.flags.webshop_signup_secret = self.secret

	def _capture_binding(self):
		self.secret = frappe.local.flags.get("webshop_signup_secret")

	def call(self, method, **kwargs):
		"""Invoke one signup endpoint as this browser.

		Args:
			method: the function from custom_webshop.api.signup.
			**kwargs: its arguments; signup_id is filled in automatically.

		Returns:
			The endpoint's envelope.
		"""
		self._restore_binding()
		if self.signup_id and "signup_id" not in kwargs:
			kwargs["signup_id"] = self.signup_id

		with capture_otps() as codes:
			result = method(**kwargs)
			self.codes.update(codes)

		if not self.signup_id:
			self.signup_id = result.get("signup_id")

		# Mirror the browser faithfully: whatever the server did to the
		# binding cookie during the call - issued it, cleared it - is what
		# this client carries into the next one. Re-asserting a
		# remembered secret instead would hide a cleared cookie, which is
		# exactly the bug the HTTP smoke test caught and these tests did
		# not.
		self._capture_binding()
		return result


def start_signup(
	account_type="Individual",
	full_name=None,
	email=None,
	phone=None,
	company_name=None,
	phone_country=None,
):
	"""Start a signup and return the client driving it.

	Args:
		account_type: "Individual" or "Company".
		full_name: defaults to a generated valid name.
		email: defaults to a generated unique address.
		phone: defaults to a generated unique Egyptian mobile.
		company_name: required for a Company signup.

	Returns:
		A (SignupClient, envelope) tuple.
	"""
	from custom_webshop.api import signup as signup_api

	client = SignupClient()
	envelope = client.call(
		signup_api.start,
		account_type=account_type,
		full_name=full_name or unique_name(),
		email=email or unique_email(),
		phone=phone or unique_phone(),
		company_name=company_name,
		phone_country=phone_country,
	)
	return client, envelope


def verify_both_channels(client):
	"""Take a started signup through email and phone verification.

	Args:
		client: the SignupClient returned by start_signup.

	Returns:
		The envelope after phone verification.
	"""
	from custom_webshop.api import signup as signup_api

	client.call(signup_api.verify_email, code=client.codes["email"])
	client.call(signup_api.send_phone_otp)
	return client.call(signup_api.verify_phone, code=client.codes["phone"])


@contextlib.contextmanager
def signup_enabled():
	"""Turn on everything the verified signup flow needs to run.

	Lifts the site-wide kill switch, enables the feature and both OTP
	channels, and sets a short resend cooldown so tests are not slowed by
	the real one.
	"""
	with signup_allowed(), signup_settings_as(
		signup_enabled=1,
		email_otp_enabled=1,
		phone_otp_enabled=1,
		email_otp_dev_mode=0,
		phone_otp_dev_mode=0,
		otp_resend_cooldown_seconds=0,
	):
		yield


@contextlib.contextmanager
def signup_allowed():
	"""Lift Website Settings' site-wide signup kill switch for the duration.

	Patched rather than written to the database. Writing it meant calling
	`frappe.clear_cache()` to make the new value visible - and
	`clear_cache` commits, so the switch escaped the test transaction
	while every other setting was still rolled back with it. That left
	tests passing or failing depending on whether anything earlier in the
	run had triggered a rollback. Patching has no transaction at all.

	`custom_webshop.api.signup` imports this function inside the guard, so
	patching it at its source is what the guard actually sees.
	"""
	from unittest.mock import patch

	with patch("frappe.website.utils.is_signup_disabled", return_value=0):
		yield


@contextlib.contextmanager
def signup_blocked_site_wide():
	"""Assert Website Settings' kill switch for the duration.

	The counterpart to signup_allowed. Tests that check the switch *stops*
	signup must set it themselves rather than lean on whatever the site
	happens to be configured as - otherwise they pass or fail depending on
	who last flipped it for a manual walkthrough.
	"""
	from unittest.mock import patch

	with patch("frappe.website.utils.is_signup_disabled", return_value=1):
		yield


@contextlib.contextmanager
def signup_settings_as(**values):
	"""Override Webshop Signup Settings fields for the duration.

	Also patched rather than written, for the same reason, and nests
	correctly: an inner override wins for the fields it names while the
	outer one still supplies the rest.

	Args:
		**values: fieldname/value pairs to apply for the duration.
	"""
	from unittest.mock import patch

	from custom_webshop.signup import settings as signup_settings

	current = signup_settings.get

	def overridden(fieldname):
		if fieldname in values:
			return values[fieldname]
		return current(fieldname)

	with patch.object(signup_settings, "get", overridden):
		yield


def purge_test_accounts():
	"""Delete the accounts a completed signup left behind.

	`linking.finalize` creates a User, Customer, Contact and identity row,
	and the endpoint that drives it commits - as it must, since the person
	is logged in immediately afterwards. So every test that runs a signup
	through to COMPLETED survives its own rollback, and a suite that does
	that a dozen times a run had accumulated two dozen accounts on this
	site before anyone noticed.

	Scoped to the two patterns only these tests produce - the generated
	`wstest-` address and the "X Middle Y" name shape `unique_name` builds
	- so it cannot match a real record. Deleted parent-last, because the
	identity row and the Customer both link to the User.
	"""
	users = frappe.get_all("User", filters={"email": ["like", "wstest-%@example.com"]}, pluck="name")

	for doctype, filters in (
		("Webshop Account Identity", {"user": ["like", "wstest-%@example.com"]}),
		("Webshop Identity Conflict", {"email_normalized": ["like", "wstest-%@example.com"]}),
		("Customer", {"customer_name": ["like", "% Middle %"]}),
		("Contact", {"first_name": ["like", "% Middle %"]}),
	):
		_purge(doctype, filters)

	for user in users:
		_delete(("User", user))

	frappe.db.commit()


def _purge(doctype, filters):
	"""Delete every row of `doctype` matching `filters`, best effort."""
	for name in frappe.get_all(doctype, filters=filters, pluck="name"):
		_delete((doctype, name))


def _delete(target):
	"""Delete one document, ignoring anything that refuses to go.

	A leftover that will not delete - because something else still links
	to it - is not worth failing a test run over; the next run tries
	again, and the data audit reports it either way.

	Each delete gets its own savepoint so undoing a failed one cannot
	also undo the deletes that already succeeded beside it. A plain
	rollback here would throw away the whole purge on the first
	stubborn record.
	"""
	doctype, name = target
	savepoint = "purge_test_accounts"
	frappe.db.savepoint(savepoint)
	try:
		frappe.delete_doc(
			doctype, name, force=True, ignore_permissions=True, delete_permanently=True
		)
	except Exception:
		frappe.db.rollback(save_point=savepoint)


def purge_test_sessions():
	"""Delete signup sessions that escaped a test's rollback.

	Two production paths commit deliberately - `session._mark_expired` and
	`otp._persist_failed_attempt` - because the exception that follows each
	one would otherwise discard the write. That is correct behaviour, and
	it is also why a test touching those paths leaves its session row
	behind when the surrounding rollback runs.

	Modules that exercise them call this from `tearDownModule` so a test
	run does not accumulate rows. Scoped to the generated `wstest-` address
	pattern, so it can only ever match data these tests made.
	"""
	for name in frappe.get_all(
		"Webshop Signup Session",
		filters={"email_normalized": ["like", "wstest-%@example.com"]},
		pluck="name",
	):
		frappe.delete_doc(
			"Webshop Signup Session", name, force=True, ignore_permissions=True, delete_permanently=True
		)
	frappe.db.commit()


def conflict_with(problem_type, **filters):
	"""The conflict carrying this problem, or None.

	One conflict is opened per signup now and each thing wrong with it is
	a row in `problems`, so a conflict is found by what is on it rather
	than by a single `conflict_type` - that field is only the headline
	the queue lists the row under.

	Args:
		problem_type: the problem to look for.
		**filters: narrowing filters on the conflict itself, e.g.
			`signup_session=` or `created_customer=`.

	Returns:
		The conflict's name, or None.
	"""
	for name in frappe.get_all("Webshop Identity Conflict", filters=filters or None,
	                           pluck="name", order_by="creation"):
		if frappe.db.exists(
			"Webshop Identity Problem", {"parent": name, "problem_type": problem_type}
		):
			return name

	return None


def problem_types(conflict):
	"""Every problem recorded on a conflict, sorted."""
	return sorted(
		frappe.get_all("Webshop Identity Problem", filters={"parent": conflict},
		               pluck="problem_type")
	)
